version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/app
    container_name: nginx
    restart: always
    ports:
      - "8881:81"
    networks:
      - myBlog

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/app
    container_name: php-fpm
    restart: always
    depends_on:
      - mysql
    networks:
      - myBlog

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - myBlog

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - myBlog

networks:
  myBlog:
    driver: bridge

volumes:
  dbdata: